const ProductsData = [
    {
        id: 1,
        model: 'RDY Trace 7MP 003',
        os: 'Windows 11 Home',
        cpu: 'Intel® Core™ i5-13400F CPU',
        gpu: 'GeForce RTX 4060 - 8GB',
        storage: '1TB M.2 NVMe SSD',
        ram: '16GB DDR5-5200MHz RAM',
        price: 1099,
        originalPrice: 1399,
        buildType: 'Prebuilt',
        isFreeShipping: true,
        imageUrl: '/RDY-Trace-7MP-003.avif',
    },
    {
        id: 2,
        model: 'RDY Lancool 003',
        os: 'Windows 11 Home',
        cpu: 'AMD Ryzen 7 7700X CPU',
        gpu: 'GeForce RTX 4070 Ti SUPER - 16GB',
        storage: '2TB M.2 NVMe SSD',
        ram: '32GB DDR5-5600MHz RGB RAM',
        price: 1999,
        originalPrice: 2249,
        buildType: 'Prebuilt',
        isFreeShipping: true,
        imageUrl: '/RDY-Lancool-003.avif',
    },
    {
        id: 3,
        model: 'Intel Core 14th Gen Extreme Gaming Daily Deal',
        os: 'Windows 11 Home',
        cpu: 'Intel® Core™ i9-14900KF CPU',
        gpu: 'NVIDIA GeForce RTX 4090 - 24GB',
        storage: '2TB WD M.2 NVMe SSD',
        ram: '32GB DDR5-5200MHz RAM',
        price: 3449,
        originalPrice: 3799,
        buildType: 'Customize',
        isFreeShipping: true,
        imageUrl: '/Intel-Core-14th-Gen-Extreme-Gaming-Daily-Deal.avif',
    },
    {
        id: 4,
        model: 'AMD Ryzen 9 Stealth Daily Deal',
        os: 'Windows 11 Home',
        cpu: 'AMD Ryzen™ 9 7900X CPU',
        gpu: 'NVIDIA GeForce RTX 4080 - 16GB',
        storage: '2TB WD M.2 NVMe SSD',
        ram: '32GB DDR5-5200MHz RAM',
        price: 2699,
        originalPrice: 2999,
        buildType: 'Customize',
        isFreeShipping: true,
        imageUrl: '/AMD-Ryzen-9-Stealth-Daily-Deal.avif',
    },
    {
        id: 5,
        model: 'RDY Y40P 003',
        os: 'Windows 11 Home',
        cpu: 'Intel® Core™ i7-14700KF CPU',
        gpu: 'GeForce RTX 4070 Ti SUPER - 16GB',
        storage: '2TB M.2 NVMe SSD',
        ram: '32GB DDR5-6000MHz RGB RAM',
        price: 2299,
        originalPrice: 2499,
        buildType: 'Prebuilt',
        isFreeShipping: true,
        imageUrl: '/RDY-Y40P-003.avif',
    },
    {
        id: 6,
        model: 'AMD Ryzen Power Up Daily Deal',
        os: 'Windows 11 Home',
        cpu: 'AMD Ryzen™ 5 7600 CPU',
        gpu: 'AMD Radeon RX 7600 - 8GB',
        storage: '2TB WD M.2 NVMe SSD',
        ram: '16GB DDR5-5200MHz RAM',
        price: 2299,
        originalPrice: 2499,
        buildType: 'Customize',
        isFreeShipping: true,
        imageUrl: '/AMD-Ryzen-Power-Up-Daily-Deal.avif',
    },
    {
        id: 7,
        model: 'Intel 13th Gen Level Up PC Daily Deal',
        os: 'Windows 11 Home',
        cpu: 'Intel® Core™ i9-13900KF CPU',
        gpu: 'GeForce RTX 4070 Ti - 12GB',
        storage: '2TB WD M.2 NVMe SSD',
        ram: '32GB DDR5-5200MHz RAM',
        price: 2309,
        originalPrice: 2559,
        buildType: 'Customize',
        isFreeShipping: true,
        imageUrl: '/Intel-13th-Gen-Level-Up-PC-Daily-Deal.avif',
    },
    {
        id: 8,
        model: 'RDY Y70 VALORANT VCTA R001',
        os: 'Windows 11 Home',
        cpu: 'AMD Ryzen™ 7 7800X3D CPU',
        gpu: 'GeForce RTX 4070 Ti SUPER - 16GB',
        storage: '2TB M.2 NVMe Gen4 SSD',
        ram: '32GB DDR5-5600MHz RGB RAM',
        price: 1279,
        originalPrice: 1479,
        buildType: 'Prebuilt',
        isFreeShipping: true,
        imageUrl: '/RDY-Y70-VALORANT-VCTA-R001.avif',
    },
];
export default ProductsData;